
# Site settings
title: Zachary and Chelsea
email: zacharytamas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The website for the wedding of Zachary Jones (zacharytamas) and Chelsea Eells.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zacharyandchelsea.com"

# Build settings
markdown: kramdown
