application: zt-project-matrimony
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: _site/index.html
  upload: _site/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: _site/\1
  upload: _site/(.*\.html)
  expiration: "1h"

- url: /(.*\.css)
  mime_type: text/css
  static_files: _site/\1
  upload: _site/(.*\.css)

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: _site/\1
  upload: _site/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: _site/\1
  upload: _site/(.*\.js)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: _site/\1
  upload: _site/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /api/.*
  script: main.app

- url: /(.+)/
  static_files: _site/\1/index.html
  upload: _site/(.+)/index.html
  expiration: "15m"

- url: /(.+)
  static_files: _site/\1/index.html
  upload: _site/(.+)/index.html
  expiration: "15m"


libraries:
- name: pycrypto
  version: "latest"
- name: webapp2
  version: latest
- name: jinja2
  version: latest

skip_files:
- ^(.*/)?.*/node_modules/.*$
- ^bower_components/.*$
- libs/.*\.dist-info/.*$
